services:
  - type: web
    name: patient-medicine-backend
    env: java
    plan: free
    region: oregon
    branch: main
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/tracker-0.0.1-SNAPSHOT.jar"
